baseURL = "http://ksontini.me/"
languageCode = "en-us"
title = "My personal place"
theme = "hugo-theme-nix"
[params]
  GithubID = "ksontini"
  Name = "Anis Ksontini"
  HeaderUsername = "anis"
  HeaderHostname = "ksontini.me"
  Email = "anis.ksontini@gmail.com"
  ProfilePicture = "https://pbs.twimg.com/profile_images/1741861820/wallpaper-632430_400x400.jpg"
  About = "info_about_you"
  nocomments = true
[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"
